// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using medii_si_platforme_de_dezvoltare_avansate_events.Data;

#nullable disable

namespace medii_si_platforme_de_dezvoltare_avansate_events.Migrations
{
    [DbContext(typeof(SibiuEventsContext))]
    [Migration("20260904052543_UpdatedEntitiesReference")]
    partial class UpdatedEntitiesReference
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("medii_si_platforme_de_dezvoltare_avansate_events.Models.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDeadline")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 4, 5, 25, 42, 820, DateTimeKind.Utc).AddTicks(8730),
                            CreatedByUserId = 1,
                            Description = "Învață tehnici avansate de ASP.NET Core, inclusiv Entity Framework și design patterns.",
                            IsActive = true,
                            Location = "Sibiu - Centrul Cultural",
                            MaxParticipants = 30,
                            RegistrationDeadline = new DateTime(2026, 9, 11, 5, 25, 42, 820, DateTimeKind.Utc).AddTicks(8730),
                            StartDate = new DateTime(2026, 9, 14, 5, 25, 42, 820, DateTimeKind.Utc).AddTicks(8730),
                            Title = "Workshop: ASP.NET Core Avançat"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 4, 5, 25, 42, 820, DateTimeKind.Utc).AddTicks(8730),
                            CreatedByUserId = 1,
                            Description = "Descoperă tendințele și best practices în cloud computing.",
                            IsActive = true,
                            Location = "Sibiu - Săli de conferințe",
                            MaxParticipants = 50,
                            RegistrationDeadline = new DateTime(2026, 9, 19, 5, 25, 42, 820, DateTimeKind.Utc).AddTicks(8730),
                            StartDate = new DateTime(2026, 9, 24, 5, 25, 42, 820, DateTimeKind.Utc).AddTicks(8730),
                            Title = "Conferință: Cloud Computing în 2025"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 9, 4, 5, 25, 42, 820, DateTimeKind.Utc).AddTicks(8730),
                            CreatedByUserId = 1,
                            Description = "Participă la competiția de programare cu premii valoroase.",
                            IsActive = true,
                            Location = "Sibiu - Spaț de lucru comun",
                            MaxParticipants = 20,
                            RegistrationDeadline = new DateTime(2026, 9, 29, 5, 25, 42, 820, DateTimeKind.Utc).AddTicks(8730),
                            StartDate = new DateTime(2026, 10, 4, 5, 25, 42, 820, DateTimeKind.Utc).AddTicks(8730),
                            Title = "Hackathon: Sibiu Tech Challenge"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 9, 4, 5, 25, 42, 820, DateTimeKind.Utc).AddTicks(8730),
                            CreatedByUserId = 1,
                            Description = "Reuni-te cu alți developeri C# și discută proiecte interesante.",
                            IsActive = true,
                            Location = "Sibiu - Cafeneaua Tech",
                            MaxParticipants = 40,
                            RegistrationDeadline = new DateTime(2026, 9, 16, 5, 25, 42, 820, DateTimeKind.Utc).AddTicks(8730),
                            StartDate = new DateTime(2026, 9, 19, 5, 25, 42, 820, DateTimeKind.Utc).AddTicks(8730),
                            Title = "Meetup: C# Developers"
                        });
                });

            modelBuilder.Entity("medii_si_platforme_de_dezvoltare_avansate_events.Models.Entities.EventRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId", "EventId")
                        .IsUnique();

                    b.ToTable("EventRegistrations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventId = 1,
                            RegistrationDate = new DateTime(2026, 9, 2, 5, 25, 42, 820, DateTimeKind.Utc).AddTicks(8730),
                            Status = 0,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            EventId = 2,
                            RegistrationDate = new DateTime(2026, 9, 3, 5, 25, 42, 820, DateTimeKind.Utc).AddTicks(8730),
                            Status = 0,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("medii_si_platforme_de_dezvoltare_avansate_events.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 4, 5, 25, 42, 820, DateTimeKind.Utc).AddTicks(8660),
                            Email = "admin@sibiuevents.com",
                            FullName = "Administrator",
                            IsActive = true,
                            Role = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 4, 5, 25, 42, 820, DateTimeKind.Utc).AddTicks(8660),
                            Email = "user@sibiuevents.com",
                            FullName = "John Doe",
                            IsActive = true,
                            Role = 0
                        });
                });

            modelBuilder.Entity("medii_si_platforme_de_dezvoltare_avansate_events.Models.Entities.Event", b =>
                {
                    b.HasOne("medii_si_platforme_de_dezvoltare_avansate_events.Models.Entities.User", "CreatedByUser")
                        .WithMany("CreatedEvents")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("medii_si_platforme_de_dezvoltare_avansate_events.Models.Entities.EventRegistration", b =>
                {
                    b.HasOne("medii_si_platforme_de_dezvoltare_avansate_events.Models.Entities.Event", "Event")
                        .WithMany("Registrations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("medii_si_platforme_de_dezvoltare_avansate_events.Models.Entities.User", "User")
                        .WithMany("EventRegistrations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("medii_si_platforme_de_dezvoltare_avansate_events.Models.Entities.Event", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("medii_si_platforme_de_dezvoltare_avansate_events.Models.Entities.User", b =>
                {
                    b.Navigation("CreatedEvents");

                    b.Navigation("EventRegistrations");
                });
#pragma warning restore 612, 618
        }
    }
}
